
service: serverless-project-py

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ses:SendEmail
      Resource: '*'

package:
  individually: true
  exclude:
    - ./** 
custom:
  environment:
    ACCOUND_ID: ${file(./env.yml):${self:provider.stage}.ACCOUND_ID}
    SENDER_EMAIL: ${file(./env.yml):${self:provider.stage}.SENDER_EMAIL}

functions:
  helloWorld:
    handler: functions/helloWorld/index.handler
    timeout: 60 # 1 min
    memorySize: 128
    package:
      include: 
        - functions/helloWorld/index.py  
        - functions/helloWorld/utils/**
    environment:
      ACCOUND_ID: ${self:custom.environment.ACCOUND_ID}
      SENDER_EMAIL: ${self:custom.environment.SENDER_EMAIL}

  sendEmailApiEndpoint:
    handler: functions/sendEmailApiEndpoint/index.handler
    timeout: 60 # 1 min
    memorySize: 128
    package:
      include: 
        - functions/sendEmailApiEndpoint/index.py  
        - functions/sendEmailApiEndpoint/utils/**
    events:
      - http:
          path: send-email
          method: post
          cors:
            origins: true
    environment:
      ACCOUND_ID: ${self:custom.environment.ACCOUND_ID}
      SENDER_EMAIL: ${self:custom.environment.SENDER_EMAIL}

plugins:
  - serverless-python-requirements